spring:
  profiles:
    active: dev # "local" will use H2, anything non-"local" will use MongoDB
  application:
    name: SampleService

threadPoolSize: 1
threadCrashLimit: 10

server:
  port: 8081
  servlet:
    context-path: /rest

mongodb:
  connectionString: mongodb+srv://cluster0admin:ZKyfj4bziDEZ0qkC@cluster0.oizco.mongodb.net/
  user: cluster0admin
  password: ZKyfj4bziDEZ0qkC
  authSource: admin
  replicaSet: atlas-j2d8vq-shard-0
  batchSize: 100
  databaseName: tradeStore
  tradeCollection: otcTrade